[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"

[build]
  command = "NODE_OPTIONS=--max_old_space_size=4096 pnpm netlify:build"
  ignore = "git diff --quiet $COMMIT_REF $CACHED_COMMIT_REF -- /"
