name: Restart CMS (docs.dfp.ch)

on:
  push:
    branches:
      - main

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Restart Dynos
        run: |
          heroku restart -a dfp-docs
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
